# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/r.rb

language: R
sudo: false
cache: packages

brew_packages:
  - libgit2

r_packages:
  - pkgdown

os:
  - linux
  - osx

r:
#  - 3.1
#  - 3.2
#  - 3.3
#  - oldrel
  - release
#  - devel

matrix:
  exclude:
    - r: 3.1
      os: osx
    - r: 3.2
      os: osx
    - r: 3.2
      os: osx
  allow_failures:
    - os: osx
      r: devel
    - os: osx
      r: 3.3

#
# first secure var is COVERALLS_TOKEN
# second is appiarium's GITHUB_PAT
#
env:
  global:
    - CI_NAME=travis-pro
    - secure: Ci43b3Has0qXyGsRN3bg9aJIVxhujZl6zQe0x0RooVLN8j7EZKnVLgfnzCdUX8e9aE9Tbc0afXiLd/JUg3OSu9HmbBXlyO8cCmM6RkVQ49aV46/WhdtLbDftSZjTLDjo927LvzGFOvbhRewfUqbDrqXupEV6vJAXWH/AEimeCT4BTHOArflLQZOOMGByncFGn0KwEJmMZgOhnKOYmpFHv7sDUltg43CJyLUPQaumULtgtHQZJdJWo59AqMrBEOnDvm5rSfF130L7xF1JxtG5H6wnYFtf3DlMTxVxfdeHTf/M973qGkQsxg4Jxs7t88FesrghbI8vpWenHh1NMNjHAl6zHIW0CwaEcMsTP2MImJ2QU4LzH3odIoK6pQEXmH+ImwA38S5y+9EWAfM3lguwHzQLCQNy/7pZ5Ji2t298hhfJamMRBHEJWxyBV+o3gtQ8w3WhKRy/xax0wx9o3emEK63GzE0FO+bWgIkWk3Hr9q5iXtW5+p1Ht4AWAF9no9ItFZHd/IiC1L3FBtrc3CJxYu9qwaVVoMIjGfy08mkvnwZeUqeYFvkEpEnVbNm/PjnZpNdcY9d3LLkvOOV9eJRkE4A0ehGHcAyc6TCHE3IlUmYNgcHxf00wPSDu1a6AAqNZawTtZ0u2PCRUToKerti9cgqbmYcskqxvlXmfDX3X/Uo=
    - secure: YG2k5WXyNUDpTDfo6zlBhChgkNNElc4yl0IEccmE9cUPLGB4BIlLJdHSpH0fq4JtSsxPGkiepW/G0lZLQCfzOKZIEtnorK7WJZ4nKQtxNFjf82/Ut38yd3qyQ/brM6Mb3BaG8Cieczf0vaxOVVWPaiJikUIuxAM1QY3Uj/yK/kcry7YmylaYtTTF4xYmYCptT6FbJOz+NkzsGUFx+JtFLMM+4kREdzTlaKxLUZYwCfd8KILYKoutJehiAywJfBGXeEayPLDlnvss0bfH0P7/VsA8CCZ0mDT16wv4acJX7TEfqXdBzWTWMJAYbbeYtVxgZqzT2tlqBBnDhsuj24NUUJqrP3eAyB47N00AhPsPUDrsb+8VZ0p62iH/ehxahcFH0Q/JOhknZasch/bLOBkWY1tUc+stzgjxS/c6JET1cKAmfh0Nvmqs7MFfHCM8MB6ZdWvC4dxDe2f+6ZiZn7jsM/AfB4CbFrMAtiPu7op8BkPp9yLCHomilf7MUMvymIT8MDmAZsvhoHJTvTSDHRItSZssRhHgZuxnXmVvP8d2aixWHWiHFmNCCzEk2sZWib5TS3DboBA9zOI1m8xjBS7sZ1HvsUQgjkxwalJTdSFB35CJdhqozfevV/jJfM+/lkVb3XuAC72grcicMILuwB+GbqtZvdotiU/QhOSf3j5Xp+c=
    - NOT_CRAN=true

before_install: echo "options(repos = c(CRAN='http://cran.rstudio.com'))" > ~/.Rprofile

after_success:
  - export CI_BRANCH=$TRAVIS_BRANCH
  - |-
    test $TRAVIS_R_VERSION_STRING = "release" && \
    Rscript - <<'EOF'
    covr::coveralls(function_exclusions = "\\.onLoad"
                    , line_exclusions   = list("R/util.R" = c(102:106))
                    )
    EOF

before_deploy:
  - Rscript -e 'withr::with_temp_libpaths(action = "prefix", code = { devtools::install(pkg = ".", reload = FALSE); pkgdown::build_site(pkg = "."); })'
  - touch gh-pages/.nojekyll

notifications:
  email: false
deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  local-dir: gh-pages
  target-branch: gh-pages
  committer-from-gh: true
  github_token: $GITHUB_PAT
  on:
    branch: master
    repo: PlantandFoodResearch/AppSecret
    condition: $TRAVIS_R_VERSION_STRING = "release"
