---
title: "Application Secrets with AppSecret"
author: "Roy Storey"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Application Secrets with AppSecret}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

This document provides a brief introduction to the R package **AppSecret** 
(Secrets managed for R Applications and Libraries). The package provides the
R6 class `app_secret` which provides management of paths, creating keys and
encryption/decryption wrapping functions from `PKI`. It is primarily designed
to work with PEM format private keys and store encrypted files in home
directories and application/library repositories.

The goal of AppSecret is to manage application secrets for users, be they
developers or test/production service users.

A PEM format public/private key pair is used to encrpyt a cryptographically
random 32 bytes which is used as a 256bit key to encrypt any number of
files, streams or data. The 256bit key and the encrpyted files may be stored
with the application, either in the repository or on disk so long as the
private key is kept secret. By default this is a user's home directory as
defined in `Sys.getenv("HOME")`.

...

## File Layout

Mention `app_secret_paths` and `here`

## Protecting Appropriately

Mention the private key (`key_file`) should **always** be inaccessible to
other users, while all other files may be accessible.

## See Also

PKI
