name: testthat tests

on:
  push:
    branches: "*"
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Install Package Dependencies
        run: |-
          Rscript -e 'install.packages(c("remotes"), repos = 'https://demo.rstudiopm.com/all/__linux__/bionic/latest');if (!all(c("remotes") %in% installed.packages())) { q(status = 1, save = "no")}'
          Rscript -e "remotes::install_deps(dependencies = TRUE, repos = 'https://demo.rstudiopm.com/all/__linux__/bionic/latest')"
      - run: |-
          Rscript -e "devtools::check()"
    container: rocker/verse:latest
